# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multy_matrix_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_matrix_main_window2(object):
    def setupUi(self, matrix_main_window2):
        matrix_main_window2.setObjectName("matrix_main_window2")
        matrix_main_window2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(matrix_main_window2)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 801, 461))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.intens2 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.intens2.setMaximum(10)
        self.intens2.setProperty("value", 5)
        self.intens2.setObjectName("intens2")
        self.gridLayout.addWidget(self.intens2, 2, 2, 1, 1)
        self.sigma1 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sigma1.setMinimum(20)
        self.sigma1.setMaximum(200)
        self.sigma1.setSingleStep(20)
        self.sigma1.setProperty("value", 20)
        self.sigma1.setObjectName("sigma1")
        self.gridLayout.addWidget(self.sigma1, 1, 1, 1, 1)
        self.nx2 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.nx2.setMinimum(1)
        self.nx2.setMaximum(5)
        self.nx2.setObjectName("nx2")
        self.gridLayout.addWidget(self.nx2, 3, 2, 1, 1)
        self.nx1 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.nx1.setMinimum(1)
        self.nx1.setMaximum(5)
        self.nx1.setObjectName("nx1")
        self.gridLayout.addWidget(self.nx1, 3, 1, 1, 1)
        self.intens4 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.intens4.setMaximum(10)
        self.intens4.setProperty("value", 5)
        self.intens4.setObjectName("intens4")
        self.gridLayout.addWidget(self.intens4, 2, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.ny2 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ny2.setMinimum(1)
        self.ny2.setMaximum(5)
        self.ny2.setObjectName("ny2")
        self.gridLayout.addWidget(self.ny2, 4, 2, 1, 1)
        self.v3 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.v3.setMinimum(-5)
        self.v3.setMaximum(5)
        self.v3.setProperty("value", 1)
        self.v3.setObjectName("v3")
        self.gridLayout.addWidget(self.v3, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.intens3 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.intens3.setMaximum(10)
        self.intens3.setProperty("value", 5)
        self.intens3.setObjectName("intens3")
        self.gridLayout.addWidget(self.intens3, 2, 3, 1, 1)
        self.v1 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.v1.setMinimum(-5)
        self.v1.setMaximum(5)
        self.v1.setProperty("value", 1)
        self.v1.setObjectName("v1")
        self.gridLayout.addWidget(self.v1, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.sigma2 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sigma2.setMinimum(20)
        self.sigma2.setMaximum(200)
        self.sigma2.setSingleStep(20)
        self.sigma2.setProperty("value", 20)
        self.sigma2.setObjectName("sigma2")
        self.gridLayout.addWidget(self.sigma2, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.ny4 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ny4.setMinimum(1)
        self.ny4.setMaximum(5)
        self.ny4.setObjectName("ny4")
        self.gridLayout.addWidget(self.ny4, 4, 4, 1, 1)
        self.ny3 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ny3.setMinimum(1)
        self.ny3.setMaximum(5)
        self.ny3.setObjectName("ny3")
        self.gridLayout.addWidget(self.ny3, 4, 3, 1, 1)
        self.intens1 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.intens1.setMaximum(10)
        self.intens1.setProperty("value", 5)
        self.intens1.setObjectName("intens1")
        self.gridLayout.addWidget(self.intens1, 2, 1, 1, 1)
        self.ny1 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ny1.setMinimum(1)
        self.ny1.setMaximum(5)
        self.ny1.setObjectName("ny1")
        self.gridLayout.addWidget(self.ny1, 4, 1, 1, 1)
        self.sigma3 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sigma3.setMinimum(20)
        self.sigma3.setMaximum(200)
        self.sigma3.setSingleStep(20)
        self.sigma3.setProperty("value", 20)
        self.sigma3.setObjectName("sigma3")
        self.gridLayout.addWidget(self.sigma3, 1, 3, 1, 1)
        self.nx4 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.nx4.setMinimum(1)
        self.nx4.setMaximum(5)
        self.nx4.setObjectName("nx4")
        self.gridLayout.addWidget(self.nx4, 3, 4, 1, 1)
        self.nx3 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.nx3.setMinimum(1)
        self.nx3.setMaximum(5)
        self.nx3.setObjectName("nx3")
        self.gridLayout.addWidget(self.nx3, 3, 3, 1, 1)
        self.sigma4 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sigma4.setMinimum(20)
        self.sigma4.setMaximum(200)
        self.sigma4.setSingleStep(20)
        self.sigma4.setProperty("value", 20)
        self.sigma4.setObjectName("sigma4")
        self.gridLayout.addWidget(self.sigma4, 1, 4, 1, 1)
        self.v4 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.v4.setMinimum(-5)
        self.v4.setMaximum(5)
        self.v4.setProperty("value", 1)
        self.v4.setObjectName("v4")
        self.gridLayout.addWidget(self.v4, 0, 4, 1, 1)
        self.v2 = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.v2.setMinimum(-5)
        self.v2.setMaximum(5)
        self.v2.setProperty("value", 1)
        self.v2.setObjectName("v2")
        self.gridLayout.addWidget(self.v2, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.xdim = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.xdim.setMinimum(100)
        self.xdim.setMaximum(1000)
        self.xdim.setSingleStep(100)
        self.xdim.setProperty("value", 400)
        self.xdim.setObjectName("xdim")
        self.gridLayout_2.addWidget(self.xdim, 0, 1, 1, 1)
        self.ydim = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ydim.setMinimum(100)
        self.ydim.setMaximum(1000)
        self.ydim.setSingleStep(100)
        self.ydim.setProperty("value", 400)
        self.ydim.setObjectName("ydim")
        self.gridLayout_2.addWidget(self.ydim, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.frms = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.frms.setMinimum(50)
        self.frms.setMaximum(1000)
        self.frms.setSingleStep(50)
        self.frms.setProperty("value", 200)
        self.frms.setObjectName("frms")
        self.gridLayout_2.addWidget(self.frms, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.run_bnt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.run_bnt.setObjectName("run_bnt")
        self.verticalLayout.addWidget(self.run_bnt)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.matrix_widget = MatrixWidget(self.splitter)
        self.matrix_widget.setObjectName("matrix_widget")
        matrix_main_window2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(matrix_main_window2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        matrix_main_window2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(matrix_main_window2)
        self.statusbar.setObjectName("statusbar")
        matrix_main_window2.setStatusBar(self.statusbar)

        self.retranslateUi(matrix_main_window2)
        self.v1.valueChanged['int'].connect(matrix_main_window2.set_v1)
        self.v2.valueChanged['int'].connect(matrix_main_window2.set_v2)
        self.v3.valueChanged['int'].connect(matrix_main_window2.set_v3)
        self.v4.valueChanged['int'].connect(matrix_main_window2.set_v4)
        self.sigma4.valueChanged['int'].connect(matrix_main_window2.set_sigma4)
        self.sigma3.valueChanged['int'].connect(matrix_main_window2.set_sigma3)
        self.sigma2.valueChanged['int'].connect(matrix_main_window2.set_sigma2)
        self.sigma1.valueChanged['int'].connect(matrix_main_window2.set_sigma1)
        self.intens1.valueChanged['int'].connect(matrix_main_window2.set_intens1)
        self.intens2.valueChanged['int'].connect(matrix_main_window2.set_intens2)
        self.intens3.valueChanged['int'].connect(matrix_main_window2.set_intens3)
        self.intens4.valueChanged['int'].connect(matrix_main_window2.set_intens4)
        self.nx1.valueChanged['int'].connect(matrix_main_window2.set_nx1)
        self.nx2.valueChanged['int'].connect(matrix_main_window2.set_nx2)
        self.nx3.valueChanged['int'].connect(matrix_main_window2.set_nx3)
        self.nx4.valueChanged['int'].connect(matrix_main_window2.set_nx4)
        self.ny1.valueChanged['int'].connect(matrix_main_window2.set_ny1)
        self.ny2.valueChanged['int'].connect(matrix_main_window2.set_ny2)
        self.ny3.valueChanged['int'].connect(matrix_main_window2.set_ny3)
        self.ny4.valueChanged['int'].connect(matrix_main_window2.set_ny4)
        self.xdim.valueChanged['int'].connect(matrix_main_window2.set_xdim)
        self.ydim.valueChanged['int'].connect(matrix_main_window2.set_ydim)
        self.frms.valueChanged['int'].connect(matrix_main_window2.set_frms)
        self.run_bnt.clicked.connect(matrix_main_window2.run_button)
        QtCore.QMetaObject.connectSlotsByName(matrix_main_window2)

    def retranslateUi(self, matrix_main_window2):
        _translate = QtCore.QCoreApplication.translate
        matrix_main_window2.setWindowTitle(_translate("matrix_main_window2", "MainWindow"))
        self.label_5.setText(_translate("matrix_main_window2", "<html><head/><body><p align=\"center\">intens</p></body></html>"))
        self.label_6.setText(_translate("matrix_main_window2", "<html><head/><body><p align=\"center\">nx</p></body></html>"))
        self.label_4.setText(_translate("matrix_main_window2", "<html><head/><body><p align=\"center\">sigma</p></body></html>"))
        self.label_3.setText(_translate("matrix_main_window2", "<html><head/><body><p align=\"center\">V</p></body></html>"))
        self.label_7.setText(_translate("matrix_main_window2", "<html><head/><body><p align=\"center\">ny</p></body></html>"))
        self.label_2.setText(_translate("matrix_main_window2", "<html><head/><body><p align=\"center\">ydim</p></body></html>"))
        self.label.setText(_translate("matrix_main_window2", "<html><head/><body><p align=\"center\">xdim</p></body></html>"))
        self.label_8.setText(_translate("matrix_main_window2", "<html><head/><body><p align=\"center\">Frames</p></body></html>"))
        self.run_bnt.setText(_translate("matrix_main_window2", "Generate and run"))

from matrix_output_widget import MatrixWidget
