# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_matrix.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(0, -3, 651, 448))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.xdim_box = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.xdim_box.setMinimum(100)
        self.xdim_box.setMaximum(1000)
        self.xdim_box.setSingleStep(100)
        self.xdim_box.setObjectName("xdim_box")
        self.verticalLayout.addWidget(self.xdim_box)
        self.ydim_box = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ydim_box.setMinimum(100)
        self.ydim_box.setMaximum(1000)
        self.ydim_box.setSingleStep(100)
        self.ydim_box.setObjectName("ydim_box")
        self.verticalLayout.addWidget(self.ydim_box)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.nx_box = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.nx_box.setMinimum(1)
        self.nx_box.setMaximum(5)
        self.nx_box.setObjectName("nx_box")
        self.verticalLayout.addWidget(self.nx_box)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.ny_box = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ny_box.setMinimum(1)
        self.ny_box.setMaximum(5)
        self.ny_box.setObjectName("ny_box")
        self.verticalLayout.addWidget(self.ny_box)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.sigma_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.sigma_slider.setMinimum(10)
        self.sigma_slider.setMaximum(1000)
        self.sigma_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sigma_slider.setObjectName("sigma_slider")
        self.verticalLayout.addWidget(self.sigma_slider)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.intense_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.intense_slider.setMinimum(1)
        self.intense_slider.setOrientation(QtCore.Qt.Horizontal)
        self.intense_slider.setObjectName("intense_slider")
        self.verticalLayout.addWidget(self.intense_slider)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.frames_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.frames_slider.setMinimum(33)
        self.frames_slider.setMaximum(628)
        self.frames_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frames_slider.setObjectName("frames_slider")
        self.verticalLayout.addWidget(self.frames_slider)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.run_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.run_btn.setObjectName("run_btn")
        self.verticalLayout.addWidget(self.run_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.matrix_widget = MatrixWidget(self.splitter)
        self.matrix_widget.setObjectName("matrix_widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">размеры матрицы</p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">nx лиссажу</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ny лиссажу</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">sigma</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">intensity</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">frames</p></body></html>"))
        self.run_btn.setText(_translate("MainWindow", "generate and show"))

from matrix_output_widget import MatrixWidget
